# This workflow uploads a Python package using Twine when a release is created.

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    # Running on macOS because wheels built on Linux are not able to be
    # uploaded to PyPI.
    # runs-on: ubuntu-latest
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Build and publish
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
