# This workflow builds the project and runs Python unit tests on every push and pull request.

name: Run Python Checks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  check-formatting:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          make install-conda
      - name: Check formatting
        run: |
          make check-formatting

  build:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Install package
        run: pip install dist/*.whl
      - name: Run unit tests
        run: |
          pip install pytest
          pytest .
